apimServiceName: prod-apim-cicd
namedValues:
  - name: plainvalue
    properties:
      displayName: plainvalue
      value: "https://www.PROD.search2.com"
  - name: Secret
    properties:
      displayName: Secret
      value: "PRODSecretT"
loggers:
diagnostics:
backends:
apis:
